### ISSUE TITLE
Can't require in node

### ISSUE THREAD

**Issue by ajbeach2** [greggman/twgl.js#7]
I can't require this library in node. This is how to reproduce

```
npm init
npm install twgl.js --save

node
> var t = require('twgl.js');
Error: Cannot find module 'twgl.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at repl:1:9
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
```

**Comment by ajbeach2** [comment]
https://github.com/greggman/twgl.js/pull/8

**Comment by greggman** [comment]
this is fixed right?

**Comment by ajbeach2** [comment]
Yeah this is fixed
